name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose -f docker/docker-compose.yml up -d

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build PHP Docker Image
        run: docker buildx build --file docker/php/Dockerfile --output "type=image,push=false" .

      - name: Build MySQL Docker Image
        run: docker buildx build --file docker/mysql/Dockerfile --output "type=image,push=false" .

      - name: Build NGINX Docker Image
        run: docker buildx build --file docker/nginx/Dockerfile --output "type=image,push=false" .
